### ISSUE TITLE
ICMPping showing Y-Axis value in seconds

### ISSUE THREAD

**Issue by takes22mango** [albinbatman/zabbix-edgemax-template#4]
Issue: Y Axis is showing ping response time in seconds (which is not usable/friendly)

Ive tried changing the Unit type from seconds to milliseconds in the template, however they also modifies the unit in which it is collecting data in.

**Comment by takes22mango** [comment]
![image](https://user-images.githubusercontent.com/65580008/82278413-7e07b080-99cd-11ea-9aa5-3e3a27946384.png)

**Comment by albinbatman** [comment]
Hi @takes22mango,

for icmp it uses the default zabbix template, maybe see if you can edit the graph under the host and calculate it accordingly?

i usually use grafana with the zabbix plugin so i can tweak it more to my needs and cosmetic liking

**Comment by albinbatman** [comment]
Hi @takes22mango,

I am closing this issue due to lack of response.
