### ISSUE TITLE
Cannot find host interface on "Zabbix server" for item key "LoadMinute".

### ISSUE THREAD

**Issue by krepelcleefton** [albinbatman/zabbix-edgemax-template#5]
I imported the template but when I try adding it to the host I keep getting an "Error updating host" Cannot find host interface on "Zabbix server" for item key "LoadMinute".

**Comment by albinbatman** [comment]
Hi @krepelcleefton,

Which Zabbix version are you using this template on? Based on the issue description it seems you are putting this template on the Zabbix server, is that correct?

**Comment by ekkzorzizten** [comment]
> I imported the template but when I try adding it to the host I keep getting an "Error updating host" Cannot find host interface on "Zabbix server" for item key "LoadMinute".

Under Configuration/Hosts/youredgerouter, on Interfaces you have to change from agent to SNMP to get it to work. If you still have Agent you will receive that error message.
