### ISSUE TITLE
Import 5.2, "Template Net Network Generic Device SNMP" Missing

### ISSUE THREAD

**Issue by johnsoncarlp** [albinbatman/zabbix-edgemax-template#6]
On import of the 5.0 template into 5.2 the error is thrown:

Cannot import template "Template EdgeMAX SNMPv2", linked template "Template Net Network Generic Device SNMP" does not exist.

Looked at template and default templates in 5.2, it appears the new name for this template is now:

Network Generic Device SNMP

**Comment by albinbatman** [comment]
Yep, feels like it get changed sporadically. I'll push a commit to sort this.

Thanks for reporting, @johnsoncarlp.

**Comment by antonio-leblanc** [comment]
Same problem here, thanks for reporting

**Comment by vincent1890** [comment]
same error here thank
`Échec import
Non-static method C50ImportConverter::convertPreprocessingSteps() should not be called statically [conf.import.php:91 → CApiWrapper->__call() → CFrontendApiWrapper->callMethod() → CApiWrapper->callMethod() → CFrontendApiWrapper->callClientMethod() → CLocalApiClient->callMethod() → CConfiguration->import() → C50ImportConverter->convert() → C50ImportConverter::convertTemplates() → C50ImportConverter::convertItems() in include/classes/import/converters/C50ImportConverter.php:113]
Non-static method C50ImportConverter::convertPreprocessingSteps() should not be called statically [conf.import.php:91 → CApiWrapper->__call() → CFrontendApiWrapper->callMethod() → CApiWrapper->callMethod() → CFrontendApiWrapper->callClientMethod() → CLocalApiClient->callMethod() → CConfiguration->import() → C50ImportConverter->convert() → C50ImportConverter::convertTemplates() → C50ImportConverter::convertItems() in include/classes/import/converters/C50ImportConverter.php:113]
Non-static method C50ImportConverter::convertPreprocessingSteps() should not be called statically [conf.import.php:91 → CApiWrapper->__call() → CFrontendApiWrapper->callMethod() → CApiWrapper->callMethod() → CFrontendApiWrapper->callClientMethod() → CLocalApiClient->callMethod() → CConfiguration->import() → C50ImportConverter->convert() → C50ImportConverter::convertTemplates() → C50ImportConverter::convertItems() in include/classes/import/converters/C50ImportConverter.php:113]
Non-static method C50ImportConverter::convertPreprocessingSteps() should not be called statically [conf.import.php:91 → CApiWrapper->__call() → CFrontendApiWrapper->callMethod() → CApiWrapper->callMethod() → CFrontendApiWrapper->callClientMethod() → CLocalApiClient->callMethod() → CConfiguration->import() → C50ImportConverter->convert() → C50ImportConverter::convertTemplates() → C50ImportConverter::convertItems() in include/classes/import/converters/C50ImportConverter.php:113]
Non-static method C50ImportConverter::convertPreprocessingSteps() should not be called statically [conf.import.php:91 → CApiWrapper->__call() → CFrontendApiWrapper->callMethod() → CApiWrapper->callMethod() → CFrontendApiWrapper->callClientMethod() → CLocalApiClient->callMethod() → CConfiguration->import() → C50ImportConverter->convert() → C50ImportConverter::convertTemplates() → C50ImportConverter::convertItems() in include/classes/import/converters/C50ImportConverter.php:113]
Non-static method C50ImportConverter::convertPreprocessingSteps() should not be called statically [conf.import.php:91 → CApiWrapper->__call() → CFrontendApiWrapper->callMethod() → CApiWrapper->callMethod() → CFrontendApiWrapper->callClientMethod() → CLocalApiClient->callMethod() → CConfiguration->import() → C50ImportConverter->convert() → C50ImportConverter::convertTemplates() → C50ImportConverter::convertDiscoveryRules() → C50ImportConverter::convertItemPrototypes() in include/classes/import/converters/C50ImportConverter.php:157]
Non-static method C50ImportConverter::convertPreprocessingSteps() should not be called statically [conf.import.php:91 → CApiWrapper->__call() → CFrontendApiWrapper->callMethod() → CApiWrapper->callMethod() → CFrontendApiWrapper->callClientMethod() → CLocalApiClient->callMethod() → CConfiguration->import() → C50ImportConverter->convert() → C50ImportConverter::convertTemplates() → C50ImportConverter::convertDiscoveryRules() → C50ImportConverter::convertItemPrototypes() in include/classes/import/converters/C50ImportConverter.php:157]
Non-static method C50ImportConverter::convertPreprocessingSteps() should not be called statically [conf.import.php:91 → CApiWrapper->__call() → CFrontendApiWrapper->callMethod() → CApiWrapper->callMethod() → CFrontendApiWrapper->callClientMethod() → CLocalApiClient->callMethod() → CConfiguration->import() → C50ImportConverter->convert() → C50ImportConverter::convertTemplates() → C50ImportConverter::convertDiscoveryRules() → C50ImportConverter::convertItemPrototypes() in include/classes/import/converters/C50ImportConverter.php:157]
Impossible d'importer le modèle "Template EdgeMAX SNMPv2", le modèle lié "Template Net Network Generic Device SNMP" n'existe pas.`

**Comment by Krumbelfix** [comment]
i had the same problem.
I've an ER-Pro (8 Port) which is not (yet?) covered by this template.

i just "fixed" this by changing the line 16:
was:
`                    <name>Template Net Network Generic Device SNMP</name>
`
to
`                    <name>Template Net Network Generic Device SNMPv2</name>
`

the import was sucessfull. Would be great if anyone can validate if this is working!

**Comment by vincent1890** [comment]
is there a solution to this incompatibility ?

**Comment by albinbatman** [comment]
Hi @johnsoncarlp &  @vincent1890,

as pointed out by @Krumbelfix and @peterfigure, you may manually replace the incompatible linked template. Unfortunately, it was changed some time during 4.x-5.x which raised this incompatibility.

Please open a PR and I can merge it with master; I do not run 5.x anymore but I might attempt a backport.
